### ISSUE TITLE
Tomorrow.io API 

### ISSUE THREAD

**Issue by cgmckeever** [fischgeek/WallDash#2]
Sorry for the random ping, but stumbled on your repo while looking for resources on the tomorrow.io API. 
Im trying to understand the API calls and struggling a bit with their docs.

In the evening (ie 11pm) I want to grab the current days total rain accumulation and in the am (ie 2am) I want to grab the potential rain for the day. However, when I run the API call, it returns start times at 9pm `2022-02-18T21:00:00-06:00` so its really confusing what the results are. Any insight into what Im doing wrong would be amazing

```
{
    "location": {
        "type": "Point",
        "coordinates": [
            41.8781,
            87.6298
        ]
    },
    "fields": [
        "temperature",
        "rainIntensity",
        "precipitationProbability",
        "precipitationType"

    ],
    "timesteps": [
        "1d"
    ],
    "timezone": "America/Chicago",
    "startTime": "2022-02-18T02:00:00-06:00",
    "endTime": "2022-02-19T02:00:00-06:00"
}
```

**Comment by fischgeek** [comment]
Probably has something to do with the timezone/format you're using when you make the call. They use `ISO 8601` formats. So, you'll have to craft your start and end timesteps in the same way (converting to your local timezone). It looks like they have a full [Postman repo](https://github.com/Tomorrow-IO-API/tomorrow-postman) you can download and play with if you haven't already.

**Comment by cgmckeever** [comment]
Thanks -- tried a bunch, and cant seem to get the API to respond to anything not 9p ... appreciate the feedback

**Comment by cgmckeever** [comment]
also even removing the `timezone` the return is still a weird startTime .. maybe that 3am Z UTC means something to 

 
```
"2022-02-18T03:00:00Z","endTime":"2022-02-19T03:00:00Z","intervals":[{"startTime":"2022-02-18T03:00:00Z"
```
```
'{
    "location": {
        "type": "Point",
        "coordinates": [
            41.8781,
            87.6298
        ]
    },
    "fields": [
        "temperature",
        "rainIntensity",
        "precipitationProbability",
        "precipitationType"

    ],
    "timesteps": [
        "1d"
    ],
    "startTime": "  2022-02-18T16:54:42Z",
    "endTime": "    2022-02-19T17:54:42Z"
}'

```

**Comment by fischgeek** [comment]
> maybe that 3am Z UTC means something

It most certainly does. I'll try it out here in a bit to see if I can figure it out.

**Comment by cgmckeever** [comment]
AMAZING -- thanks for the assist. Even their docs have `1d` returns being offset by an amount. versus

**Comment by cgmckeever** [comment]
Their HQ is in Tel Aviv, which is UTC+3 ... that might be where it all stems from. Really mucks with what the TS mean though as 9am TS on a day roll-up is weird IMO

**Comment by fischgeek** [comment]
Seems standard. They can't/shouldn't have to account for all timezones. You have to convert when you get the response back.

**Comment by cgmckeever** [comment]
But they do account for the timezone if you send a timezone in the payload. 
it just seems that them defining a day rollup either not at midnight of the day timezone or midnight at UTC is odd. It just makes me second guess if their day is defined at the start of a day UTC+3 (tel aviv) which then makes me wonder if the returned values are also based on that 'day' and not the local 24 hour window -- I cant imagine that being the case, I need to compare some actual known numbers with the returns

**Comment by fischgeek** [comment]
Your midnight is not the same as UTC's midnight. So you need to account for that in your `timezone` parameter. Or, I'm not fully understanding your issue here. If a show airs on television at 7/6 Central, then I (being in CST) watch it at 6:00PM. My sister in FL watches it at the same time but her clock reads 7:00PM. Is this not the same scenario?

**Comment by cgmckeever** [comment]
I get that ... the issue Im saying is that its calling the `start of the day `9p` which isnt midnight UTC or any actual valid time I would call the start of a day... 
The timezone parameter changes the response values to the timezone you want, but I dont want my start of the day (24 hour window) to be 9pm. I want a true 24 hour window of the current day, starting at midnight my timezone.

I just got a email back from support. The `startTime` for `1d` is the start of a 24 hour window, so as I thought when my response says `"startTime":"2022-02-18T03:00:00Z"` that weather of 24 hours from that moment in time forward, which is not at all what I want. That at least confirms what I thought was off. 

Since Im on the free version, I need to play with this some since I cant request further back thatn -6 hours.
